/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  safelist: [
    { pattern: /^(bg|text|border|ring)-(green|red|orange)(-[a-z]+)?$/ },
  ],
  theme: {
    borderRadius: {
      DEFAULT: '0',
      none: '0',
      sm: '0',
      md: '0',
      lg: '0',
      xl: '0',
      '2xl': '0',
      '3xl': '0',
      full: '0',
    },
    extend: {
      fontSize: {
        /* Heading sizes: +20% from base, rounded to 8px grid */
        'heading-1': ['96px', { lineHeight: '1.1' }],
        'heading-2': ['40px', { lineHeight: '1.2' }],
        'heading-3': ['32px', { lineHeight: '1.25' }],
        'heading-4': ['24px', { lineHeight: '1.3' }],
        'heading-5': ['16px', { lineHeight: '1.4' }],
        /* Style Guide v2 – typografická škála */
        'rta-h1': ['64px', { lineHeight: '1' }],
        'rta-h2': ['48px', { lineHeight: '1.1' }],
        'rta-h3': ['36px', { lineHeight: '1.1' }],
        'rta-h4': ['32px', { lineHeight: '1.35' }],
        'rta-h5': ['24px', { lineHeight: '1.4' }],
        'rta-h6': ['20px', { lineHeight: '1.45' }],
        /* Rich Text Standard (Instrument Sans) – jiné velikosti než Nokturo */
        'rta-std-h1': ['44px', { lineHeight: '1.2', letterSpacing: '-0.04em' }],
        'rta-std-h2': ['36px', { lineHeight: '1.25', letterSpacing: '-0.03em' }],
        'rta-std-h3': ['24px', { lineHeight: '1.3', letterSpacing: '-0.02em' }],
        'rta-std-h4': ['24px', { lineHeight: '1.35', letterSpacing: '-0.01em' }],
        'rta-std-h5': ['20px', { lineHeight: '1.4', letterSpacing: '-0.01em' }],
        'rta-p-s': ['14px', { lineHeight: '1.6' }],
        'rta-p-m': ['16px', { lineHeight: '1.6' }],
        'rta-p-l': ['20px', { lineHeight: '1.4' }],
        'rta-quote': ['36px', { lineHeight: '1.2' }],
        'rta-tag': ['12px', { lineHeight: '1' }],
        'label': ['16px', { lineHeight: '1' }],
        'button-text': ['16px', { lineHeight: '1' }],
      },
      fontFamily: {
        sans: ['Instrument Sans', 'sans-serif'],
        /* H1/H2 v rich textu – IvyPresto Headline z Adobe Fonts */
        headline: ['ivypresto-headline', 'Georgia', 'serif'],
        body: ['Instrument Sans', 'sans-serif'],
      },
      colors: {
        /* Semantic theme tokens – use these for bg/border, not hardcoded hex */
        page: 'var(--bg-page)',
        header: 'var(--bg-header)',
        surface: 'var(--bg-surface)',
        elevated: 'var(--bg-elevated)',
        borderDefault: 'var(--border-default)',
        overlay: 'var(--overlay)',
        /* Bíločerná paleta po 5% (0 = bílá, 100 = černá) */
        nokturo: {
          0: '#FFFFFF',
          5: '#F2F2F2',
          10: '#E6E6E6',
          15: '#D9D9D9',
          20: '#CCCCCC',
          25: '#BFBFBF',
          30: '#B3B3B3',
          35: '#A6A6A6',
          40: '#999999',
          45: '#8C8C8C',
          50: '#808080',
          55: '#737373',
          60: '#666666',
          65: '#595959',
          70: '#4D4D4D',
          75: '#404040',
          80: '#333333',
          85: '#262626',
          90: '#1A1A1A',
          95: '#0D0D0D',
          100: '#000000',
          /* Aliases pro zpětnou kompatibilitu */
          '50': '#FAFAFA',
          '100': '#F5F5F5',
          '200': '#E6E6E6',
          '300': '#D9D9D9',
          '350': '#B3B3B3',
          '400': '#A6A6A6',
          '500': '#737373',
          '600': '#525252',
          '700': '#404040',
          '800': '#262626',
          '850': '#1A1A1A',
          '900': '#171717',
          '950': '#0A0A0A',
        },
        /* Jediné povolené barvy mimo bíločernou */
        green: {
          DEFAULT: '#127346',
          fg: '#94FFCD',
        },
        red: {
          DEFAULT: '#6A0B0B',
          fg: '#FFA3A3',
        },
        orange: {
          DEFAULT: '#D98320',
          fg: 'rgba(255, 241, 224, 1)',
        },
        mention: '#D400FF',
      },
      transitionDuration: {
        DEFAULT: '0ms',
        0: '0ms',
        75: '0ms',
        100: '0ms',
        150: '0ms',
        200: '0ms',
        300: '0ms',
        500: '0ms',
        700: '0ms',
        1000: '0ms',
      },
    },
  },
  plugins: [],
};
